graph TD
%% Generated: /home/dnnrly/projects/gsl-lang/tmp/gsl-query -f q1-deprecation-impact.gql -i model.gsl | /home/dnnrly/projects/gsl-lang/tmp/gsl-diagram -f mermaid -t graph

  catalog_cache["Redis"]
  legacy_promo_calc --> catalog_cache
  legacy_promo_calc["legacy_promo_calc"]
  returns_system --> legacy_promo_calc
  returns_system["returns_system"]
