# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Pascal Dennerly.
(subgraph node.id == "web_portal" traverse out all) as REACH | from * | (subgraph node in @highly_confidential_data) as HC | REACH & HC