# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Pascal Dennerly.
(subgraph node in @application traverse both 1) as APP | from * | (subgraph node in @restricted traverse both 1) as REST | APP & REST