graph TD
%% Generated: /home/dnnrly/projects/gsl-lang/tmp/gsl-query -f q4-derivatives-cleared.gql -i model.gsl | /home/dnnrly/projects/gsl-lang/tmp/gsl-diagram -f mermaid -t graph

  alpha_bank --> ccp
  alpha_bank["alpha_bank"]
  beta_bank --> ccp
  beta_bank["beta_bank"]
  brokerage --> ccp
  brokerage["brokerage"]
  ccp["ccp"]
