graph TD
%% Generated: /home/dnnrly/projects/gsl-lang/tmp/gsl-query -f q6-interbank-lending.gql -i model.gsl | /home/dnnrly/projects/gsl-lang/tmp/gsl-diagram -f mermaid -t graph

  alpha_bank --> beta_bank
  alpha_bank["alpha_bank"]
  beta_bank --> gamma_bank
  beta_bank["beta_bank"]
  delta_bank --> alpha_bank
  delta_bank["delta_bank"]
  gamma_bank --> delta_bank
  gamma_bank["gamma_bank"]
