graph TD
%% Generated: /home/dnnrly/projects/gsl-lang/tmp/gsl-query -f q5-interview-only.gql -i model.gsl | /home/dnnrly/projects/gsl-lang/tmp/gsl-diagram -f mermaid -t graph

  emailer["emailer"]
  reporting_job --> emailer
  reporting_job["reporting_job"]
