#!/usr/bin/env bash
# Optional structural gate for GSL models generated by the gsl-modelling skill.
#
# If gsl-query is on PATH, canonicalise the input model (the canonicalisation
# runs the full parser and reports warnings) and pass through the exit status.
# If gsl-query is NOT available, report that validation could not run and exit
# 127, so a missing tool is never mistaken for a validated model.
#
# Usage: validate.sh model.gsl
#
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Pascal Dennerly.
set -euo pipefail

[ $# -eq 1 ] || { echo "usage: $0 model.gsl" >&2; exit 2; }
model="$1"
[ -f "$model" ] || { echo "no such file: $model" >&2; exit 2; }

if ! command -v gsl-query >/dev/null 2>&1; then
  echo "gsl-query not found - structural validation unavailable" >&2
  echo "install via 'go install github.com/dnnrly/gsl-lang/cmd/gsl-query@latest' or 'make build'" >&2
  exit 127
fi

echo "validating $model with gsl-query..." >&2
gsl-query "" < "$model"