graph TD
%% Generated: gsl-query -f q1-europe.gql -i model.gsl | gsl-diagram -f mermaid -t graph

  customer_api["Customer API"]
  web_portal["Web Portal"]
  order_service["order_service"]
  customer_store["customer_store"]
  notification_service["notification_service"]
  catalogue_store["catalogue_store"]
  observability["Observability"]
  customer_service["customer_service"]
  event_bus["Event Bus"]
  catalogue_service["catalogue_service"]
  order_store["order_store"]

  web_portal --> customer_api
  web_portal --> catalogue_service
  customer_api --> order_service
  customer_api --> customer_service
  order_service --> order_store
  order_service --> customer_service
  order_service --> catalogue_service
  order_service --> event_bus
  customer_service --> customer_store
  notification_service --> event_bus
  notification_service --> event_bus
  notification_service --> customer_store
  catalogue_service --> catalogue_store
  event_bus --> observability
