graph TD
%% Generated: /home/dnnrly/projects/gsl-lang/tmp/gsl-query -f q3-monolith-neighbourhood.gql -i model.gsl | /home/dnnrly/projects/gsl-lang/tmp/gsl-diagram -f mermaid -t graph

  legacy_monolith --> orders_db
  legacy_monolith --> payment_gateway
  legacy_monolith --> queue
  legacy_monolith["legacy_monolith"]
  orders_db["orders_db"]
  orders_ui --> legacy_monolith
  orders_ui["orders_ui"]
  payment_gateway["payment_gateway"]
  queue["queue"]
  scheduler --> legacy_monolith
  scheduler["scheduler"]
